### ISSUE TITLE
[BUG] addInitScript and exposeFunction navigation stuck

### ISSUE THREAD

**Issue by kbourro** [Kaliiiiiiiiii-Vinyzu/patchright#126]
### System info
- Playwright Version: [v1.55.2]
- Operating System: [Windows 11]
- Browser: [Chrome]
- Other info:

### Source code
```javascript
import patchright from "patchright";

const browserInstance = await patchright.chromium.launch({
  channel: "chrome",
  headless: false,
  viewport: null,
});

const context = await browserInstance.newContext();
const page = await context.newPage();

await page.addInitScript(() => {
  console.log("addInitScript");
});
console.log("Navigating to Pinterest...");
await page.goto("https://pinterest.com", {
  waitUntil: "load",
  timeout: 5000,
});
```

**Steps**
- Run the script

**Expected**

Navigate to pinterest

**Actual**

It stuck on loading at about:blank page, page.exposeFunction does the same

**Comment by kbourro** [comment]
Based on few tests it seems that ```javascript async fulfill(response) ``` inside crNetworkManager is very slow for big websites. It can be optimized.

**Comment by kbourro** [comment]
Please check PR #127 
Fixed my issue with big html, and i found another issue on the same example that google refused to run script as CSP was wrong.

**Comment by kbourro** [comment]
Maybe this fix "InitScript Timing (4 Failing Tests)" ?

**Comment by Vinyzu** [comment]
Solved, thank you for your PR!
This didnt fix "InitScript Timing (4 Failing Tests)" though, as these issues lie deeper in the actual CDP/Javascript Runtime Evaluation.
