### ISSUE TITLE
[BUG] addPageBinding is not defined when using page.exposeFunction

### ISSUE THREAD

**Issue by makkar-puneet** [Kaliiiiiiiiii-Vinyzu/patchright#69]
### System info
- Patchright Version: [1.52.0]
- Operating System: [Mac]
- Browser: [Chromium]
- Other info:

### Sample Code
```
import { chromium } from 'patchright';

(async () => {
  const browser = await chromium.launch();
  const page = await browser.newPage();

  // Expose a Node.js function to the page
  await page.exposeFunction('myNodeFunc', async (msg) => {
    console.log('Message from browser:', msg);
    return `Received: ${msg}`;
  });

  await page.setContent(`
    <script>
      (async () => {
        const response = await window.myNodeFunc("Hello from the browser");
        console.log(response);
      })();
    </script>
  `);

  await page.waitForTimeout(1000); // give time to see the console log
  await browser.close();
})();
```

### Error
Works fine on playwright 1.52.0 but fails with following error on patchright-1.52.0

```
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^
page.exposeFunction: addPageBinding is not defined
    at async index.js:9:3 {
  name: 'ReferenceError'
}
```

**Comment by makkar-puneet** [comment]
thanks a lot @Vinyzu for the changes. 
when can we expect patchright@1.52.0 to have these changes.

**Comment by Vinyzu** [comment]
Hopefully this week, not sure though

**Comment by Vinyzu** [comment]
Fixed in the latest version on pypi/npm.

**Comment by makkar-puneet** [comment]
reinstalled the package. using npm. I am still seeing the issue in patchright@1.52.0

**Comment by Vinyzu** [comment]
Newest Version is [1.52.3](https://www.npmjs.com/package/patchright/v/1.52.3).
